[package]
name = "flair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "flair"
path = "src/main.rs"


[dependencies]
chrono = "0.4.33"
dotenv = "0.15.0"
postgres = "0.19.7"
